set -g mouse on

# Use Vim key bindings.
setw -g mode-keys vi
set -g status-keys vi

run-shell ~/.dotfiles/tmux-better-mouse-mode/scroll_copy_mode.tmux
set-option -g default-terminal "screen-256color"
